Clean architecture
go-park-mail-ru/2020_1_no_homomorphism pull request #29
Opened 2020-03-04 19:29 UTC by mortawe

2020-03-04 20:53 UTC, hackallcode requested changes

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +	repository3 "no_homomorphism/internal/pkg/track/repository"
Сделай читаемые алиасы

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +	sesRep := repository.SessionRepository{
Сделай функции по созданию репозиториев (там же, где и сам репозиторий объявляется). `sesRep := repository.NewSessionRepository()`

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +			"test": &models.User{
Как раз эти тестовые пользователи спрячутся во внутреннюю реализацию репозитория

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +	if err := http.ListenAndServe(":8081", c.Handler(r)); err != nil {
Очень неявно навешиваешься CORS, лучше отдельной строкой

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +	c := cors.New(cors.Options{
Вынеси в internal/pkg/middleware/cors.go

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +	fmt.Printf("Starts server at 8081\n")
Может Println в данном случае лучше подходит?

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_new.go
> +package server
Странное название файла)
Просто server.go

2020-03-04 20:53 UTC, hackallcode commented on internal/app/server/server_test.go
> +	api := main.InitStorages()
Оно работает? Я не нашел такой функции что-то..

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/models/user_test.go
>  func TestNewUsersStorage(t *testing.T) {
Аналогичный вопрос: работает?

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/session/repository/session_mem_repo.go
> +	Sessions map[uuid.UUID]*models.User
Работа с map - потоконебезопасная, так что если используешь подобного рода репозиторий, надо обернуть в mutex

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/session/repository.go
> +	PrintSessionList()
Зачем такое в интерфейсе? Если для дебага, то лучше не надо

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/session/usecase.go
> +	PrintSessionList()
Аналогично: тут оно не надо

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/session/usecase/session.go
> +		Expires:  time.Now().Add(72 * time.Hour),
Может лучше месяц?

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/track/delivery/handler.go
> +		w.WriteHeader(http.StatusBadRequest)
А отвечать мы ничего не будем? Просто статус? Не, надо возвращать ошибку, желательно в json

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/track/repository.go
> +type Repository interface {
Лучше называть репозитории TrackRepository и т.п., чтобы не конфликтовали (хотя может оно и не будет конфликтовать)

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +		log.Printf("permission denied: %s", err)
Аналогично, надо возвращать, что за ошибка

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	http.SetCookie(w, h.SessionUC.Create(user))
h.SessionUC не возвращает ошибку?

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); err != nil {
О нет, тут этого быть не должно, это usecase (вдруг решим поменять алгоритм хеширования, а он разбросан)

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	if _, err := h.SessionUC.GetUserBySessionID(sid); err != nil {
Думаю, что это лишнее: просто сбрось куку и все

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	w.WriteHeader(http.StatusOK)
Можно это вынести в middleware или просто в функцию общую

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	var kek []byte
Не, фигня, давай нормальное название

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	fmt.Println(r.Header)
Дебаг лишний как по мне

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +		fmt.Println("noooooooooooooooooooo")
Очень информативно (нет)

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +	}
Это выносится в auth middleware

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +func (h *Handler) CheckAuth(w http.ResponseWriter, r *http.Request) {
Если будет auth middleware, то тут как раз всего одна строка будет

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/repository.go
> +	PrintUserList()
Надо убрать

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/usecase.go
> +	PrintUserList()
Лишнее

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/usecase/usecase.go
> +	uc.Repository.UpdateAvatar(user, uc.AvatarDir+"default.png")
filepath.join

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/usecase/usecase.go
> +	filePath := os.Getenv("MUSIC_PROJ_DIR") + uc.AvatarDir + fileName + "." + contentType
filepath.join

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/usecase/usecase.go
> +	contentType := "png"
Только png?

2020-03-04 20:53 UTC, hackallcode commented on internal/pkg/user/usecase/usecase.go
> +	uc.Repository.UpdateAvatar(user, uc.AvatarDir+fileName+"."+contentType)
filepath.join или что-то подобное

2020-03-05 11:50 UTC, mortawe commented on internal/app/server/server_test.go
> +	api := main.InitStorages()
нет

2020-03-05 11:50 UTC, mortawe commented on internal/pkg/models/user_test.go
>  func TestNewUsersStorage(t *testing.T) {
нет, перепишу тесты позднее

2020-03-05 22:50 UTC, hackallcode commented on internal/app/server/server_test.go
> +	api := main.InitStorages()
Может тогда убрать?

2020-03-05 22:50 UTC, hackallcode commented on internal/pkg/models/user_test.go
>  func TestNewUsersStorage(t *testing.T) {
Может тогда убрать?

2020-03-06 10:52 UTC, hackallcode requested changes

2020-03-06 10:52 UTC, hackallcode commented on internal/pkg/session/usecase/session.go
> +		for i := 0; i < 5; i++ {
Что это?

2020-03-06 10:52 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
> +		middleware.MarshallAndSendError(err, w)
Middleware делают не так

2020-03-06 10:52 UTC, hackallcode commented on internal/pkg/middleware/jsonError.go
> +func MarshallAndSendError(err error, w http.ResponseWriter) {
Неправильная в плане интерфейса middleware

2020-03-08 12:22 UTC, hackallcode approved these changes

2020-03-08 12:26 UTC, merged