Predev
go-park-mail-ru/2020_1_no_homomorphism pull request #8
Opened 2020-02-26 12:10 UTC by bulletmys

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	userId, ok := api.Sessions[sessionId]
Это надо вынести в функцию репозитория

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	requestedID, err := strconv.Atoi(mux.Vars(r)["id"])
А что если нет id в vars?

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	err = saveFile(file, userId.String())
Надо добавить проверку сигнатур файлов

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	api.Mutex.Lock()
Аналогично вынести в репозиторий

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +		Expires: time.Now().Add(10 * time.Hour),
Авторизация на 10 часов? Не мало ли?

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	id := api.Sessions[sid]
А если нет такого?

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	if newUserData.Password != user.Password {
Нужен пароль, чтобы поменять настройки?

2020-02-26 16:49 UTC, hackallcode commented on handlers/user_test.go
> +				Password: "123",
Пароли в открытом виде хранить нельзя

2020-02-26 16:49 UTC, hackallcode commented on handlers/user.go
> +	profileJson, err := json.Marshal(profile)
Мы в  итоге не вместе с паролем вернем пользователя?

2020-02-26 16:49 UTC, hackallcode commented on models/track.go
> +		Link:     "https://d4.hotplayer.ru/download/4219e191e9078c11d1e7825344da42b8/287373405_456239023/12a221000968e-51fb57871d78-d722a1dfefb/HIS%20NAME%20IS%20-%20JOHN%20CENA%20%232.mp3",
Загрузили бы к себе на сайт...

2020-02-26 19:03 UTC, mortawe commented on handlers/user.go
> +	profileJson, err := json.Marshal(profile)
без пароля, так как в профайле не хранятся приватные данные

2020-02-26 21:53 UTC, hackallcode requested changes

2020-02-26 21:53 UTC, hackallcode commented on handlers/user.go
> +	filePath := avatarDir + userId + ".png" //todo подставлять формат файла
Может все-таки подставим?

2020-02-26 21:53 UTC, hackallcode commented on handlers/user.go
> +	path := api.AvatarDir + userId.String() + ".png"
Надо бы получать урл аватарки из репозитория

2020-02-26 21:53 UTC, hackallcode commented on handlers/user.go
> +	file, err := os.Open(api.AvatarDir + userId.String() + ".png")
В трех местах эта странная генерация.. Хотя бы в одно место надо бы вынести

2020-02-26 21:53 UTC, hackallcode commented on handlers/user.go
> +		_, authorized = api.Sessions[id]
А потом из-за отсутствия mutex при запуске тестов --race будет ругань в консоль

2020-02-26 21:53 UTC, hackallcode commented on handlers/user.go
> +	fmt.Println(login)
Дебаг

2020-02-26 21:53 UTC, hackallcode commented on handlers/user.go
> +	login := vars["profile"]
А если нет такого?

2020-02-26 21:53 UTC, hackallcode commented on main.go
> +		AvatarDir:    "/home/ubuntu/2020_1_no_homomorphism/static/img/avatar/",
Должно быть в конфиге

2020-02-26 21:53 UTC, hackallcode commented on main.go
> +	r.HandleFunc("/track/{id:[0-9]+}", api.GetTrackHandler).Methods("GET")
Надо будет потом написать красивый роутер по конфигу

2020-02-26 21:53 UTC, hackallcode commented on models/user.go
> +		return uuid.UUID{0}, errors.New("пользователь с таким логином уже существует")
Ошибки на русском не очень хорошо, особенно когда все другие на английском

2020-02-27 14:43 UTC, hackallcode approved these changes

2020-02-27 14:56 UTC, 4taa approved these changes

2020-02-27 14:57 UTC, merged